
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://murxvnwhxvtfkajcwenw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11cnh2bndoeHZ0ZmthamN3ZW53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMzczMDgsImV4cCI6MjA1OTkxMzMwOH0.e_8xx3dOjJSc5BW94O1OixzpTw46VJr0MCN8O0ycE6g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
